# Generated by Django 3.1.2 on 2020-11-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='id categoria')),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('idPeriodista', models.AutoField(primary_key=True, serialize=False, verbose_name='id periodista')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre periodista')),
                ('email', models.CharField(max_length=20, verbose_name='email periodista')),
                ('foto', models.ImageField(upload_to='', verbose_name='foto periodista')),
                ('contraseña', models.CharField(max_length=10, verbose_name='contraseña periodista')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('contraseña', models.CharField(max_length=20, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.AutoField(primary_key=True, serialize=False, verbose_name='id noticia')),
                ('titulo', models.CharField(max_length=20, verbose_name='titulo noticia')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripcion noticia')),
                ('fecha', models.DateField(verbose_name='fecha publicacion')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.categoria')),
                ('idPeriodista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.periodista')),
            ],
        ),
    ]
