# Generated by Django 3.1.2 on 2020-11-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default=1, upload_to='', verbose_name='imagen noticia'),
            preserve_default=False,
        ),
    ]
