# Generated by Django 3.1.2 on 2020-11-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.CharField(max_length=20, verbose_name='imagen noticia'),
        ),
    ]
