# Generated by Django 3.1.2 on 2020-11-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_auto_20201108_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodista',
            name='foto',
            field=models.ImageField(max_length=20, upload_to='', verbose_name='foto periodista'),
        ),
    ]
