# Generated by Django 3.1.2 on 2020-11-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_auto_20201128_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodista',
            name='foto',
            field=models.CharField(max_length=20, verbose_name='foto periodista'),
        ),
    ]
